# Model arguments
model_name_or_path: /mnt/data2/yuhaoliu/sft_models/Qwen2-7B_SFT-OpenHermes-2.5-Standard
torch_dtype: null

# Data training arguments
# For definitions, see: src/h4/training/config.py
dataset_mixer:
  RLHFlow/UltraFeedback-preference-standard: 1.0
dataset_splits:
- train
preprocessing_num_workers: 32

# DPOTrainer arguments
bf16: true
beta: 0.1
weight_decay: 0.01
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
learning_rate: 5.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_length: 4096
max_prompt_length: 32768
num_train_epochs: 1
optim: paged_adamw_32bit
output_dir: /mnt/data2/yuhaoliu/trl_dpo/qwen2-7b-dpo
per_device_train_batch_size: 4
save_strategy: "steps"
save_steps: 1000
save_total_limit: 1
seed: 42
warmup_ratio: 0.03
report_to: wandb